# encoding=utf-8
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tank_game_Menu.py']
DATA_FILES = ['unlocked.txt', 'options.txt', 'images', 'music',
              'custom_levels', 'levels']
OPTIONS = {'iconfile': 'tank_game.icns',
           'excludes': ['numpy', 'scipy', 'matplotlib'],
           'includes': ['pygame'],
           'argv_emulation': True}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    data_files=DATA_FILES,
    setup_requires=['py2app'],
)
